// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-codebase-operator/v2/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCDStageDeployHandler creates a new instance of MockCDStageDeployHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCDStageDeployHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCDStageDeployHandler {
	mock := &MockCDStageDeployHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCDStageDeployHandler is an autogenerated mock type for the CDStageDeployHandler type
type MockCDStageDeployHandler struct {
	mock.Mock
}

type MockCDStageDeployHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCDStageDeployHandler) EXPECT() *MockCDStageDeployHandler_Expecter {
	return &MockCDStageDeployHandler_Expecter{mock: &_m.Mock}
}

// ServeRequest provides a mock function for the type MockCDStageDeployHandler
func (_mock *MockCDStageDeployHandler) ServeRequest(context1 context.Context, cDStageDeploy *v1.CDStageDeploy) error {
	ret := _mock.Called(context1, cDStageDeploy)

	if len(ret) == 0 {
		panic("no return value specified for ServeRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.CDStageDeploy) error); ok {
		r0 = returnFunc(context1, cDStageDeploy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCDStageDeployHandler_ServeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeRequest'
type MockCDStageDeployHandler_ServeRequest_Call struct {
	*mock.Call
}

// ServeRequest is a helper method to define mock.On call
//   - context1 context.Context
//   - cDStageDeploy *v1.CDStageDeploy
func (_e *MockCDStageDeployHandler_Expecter) ServeRequest(context1 interface{}, cDStageDeploy interface{}) *MockCDStageDeployHandler_ServeRequest_Call {
	return &MockCDStageDeployHandler_ServeRequest_Call{Call: _e.mock.On("ServeRequest", context1, cDStageDeploy)}
}

func (_c *MockCDStageDeployHandler_ServeRequest_Call) Run(run func(context1 context.Context, cDStageDeploy *v1.CDStageDeploy)) *MockCDStageDeployHandler_ServeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.CDStageDeploy
		if args[1] != nil {
			arg1 = args[1].(*v1.CDStageDeploy)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCDStageDeployHandler_ServeRequest_Call) Return(err error) *MockCDStageDeployHandler_ServeRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCDStageDeployHandler_ServeRequest_Call) RunAndReturn(run func(context1 context.Context, cDStageDeploy *v1.CDStageDeploy) error) *MockCDStageDeployHandler_ServeRequest_Call {
	_c.Call.Return(run)
	return _c
}
