version: "1"
run:
  timeout: 5m
  allow-parallel-runners: true
issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
    - path: ".*_test\\.go$"
      linters:
        - errcheck
linters:
  disable-all: true
  enable:
    - copyloopvar
    - errcheck
    - gci
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wsl

linters-settings:
  revive:
    rules:
      - name: comment-spacings
  gci:
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # The default order of sections is `standard > default > custom > blank > dot`,
    # If `custom-order` is `true`, it follows the order of `sections` option.
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/epam) # Custom section: groups all imports with the specified Prefix.
      - prefix(github.com/epam/edp-codebase-operator) # Custom section: groups all imports with the specified Prefix.

    # Skip generated files.
    skip-generated: true

    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    # Default: false
    custom-order: true
