with-expecter: True
inpackage: False
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName | lower}}_mock.go"
issue-845-fix: True
disable-version-string: True
resolve-type-alias: False
packages:
  github.com/epam/edp-codebase-operator/v2/controllers/cdstagedeploy/chain:
    interfaces:
      CDStageDeployHandler:
  github.com/epam/edp-codebase-operator/v2/controllers/codebase/service/chain/handler:
    interfaces:
      CodebaseHandler:
  github.com/epam/edp-codebase-operator/v2/pkg/client/jira:
    interfaces:
      Client:
  github.com/epam/edp-codebase-operator/v2/pkg/gerrit:
    interfaces:
      Client:
  github.com/epam/edp-codebase-operator/v2/pkg/git:
    interfaces:
      Git:
  github.com/epam/edp-codebase-operator/v2/pkg/gitprovider:
    interfaces:
      GitProjectProvider:
  github.com/epam/edp-codebase-operator/v2/pkg/tektoncd:
    interfaces:
      TriggerTemplateManager:
  github.com/epam/edp-codebase-operator/v2/pkg/autodeploy:
    interfaces:
      Manager:
