ignore:
  - "**/cache/**"
  - "**/config/**"
  - "**/deploy-templates/**"
  - "**/templates/**"
  - "**/*_controller.go"
  - "**/zz_generated.deepcopy.go"
  - "**/*_types.go"
  - "**/factory.go"
  - "**/mock_*.go"
  - "**/*_mock.go"
  - "**/*.groovy"
  - "**/.github/**"
  - "**/api/**"
  - "**/tests/**"
  - "**/hack/**"
  - "main.go"
