// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-codebase-operator/v2/pkg/gitprovider"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitProjectProvider creates a new instance of MockGitProjectProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitProjectProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitProjectProvider {
	mock := &MockGitProjectProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitProjectProvider is an autogenerated mock type for the GitProjectProvider type
type MockGitProjectProvider struct {
	mock.Mock
}

type MockGitProjectProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitProjectProvider) EXPECT() *MockGitProjectProvider_Expecter {
	return &MockGitProjectProvider_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function for the type MockGitProjectProvider
func (_mock *MockGitProjectProvider) CreateProject(ctx context.Context, gitlabURL string, token string, fullPath string, settings gitprovider.RepositorySettings) error {
	ret := _mock.Called(ctx, gitlabURL, token, fullPath, settings)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, gitprovider.RepositorySettings) error); ok {
		r0 = returnFunc(ctx, gitlabURL, token, fullPath, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitProjectProvider_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockGitProjectProvider_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - gitlabURL string
//   - token string
//   - fullPath string
//   - settings gitprovider.RepositorySettings
func (_e *MockGitProjectProvider_Expecter) CreateProject(ctx interface{}, gitlabURL interface{}, token interface{}, fullPath interface{}, settings interface{}) *MockGitProjectProvider_CreateProject_Call {
	return &MockGitProjectProvider_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, gitlabURL, token, fullPath, settings)}
}

func (_c *MockGitProjectProvider_CreateProject_Call) Run(run func(ctx context.Context, gitlabURL string, token string, fullPath string, settings gitprovider.RepositorySettings)) *MockGitProjectProvider_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 gitprovider.RepositorySettings
		if args[4] != nil {
			arg4 = args[4].(gitprovider.RepositorySettings)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitProjectProvider_CreateProject_Call) Return(err error) *MockGitProjectProvider_CreateProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitProjectProvider_CreateProject_Call) RunAndReturn(run func(ctx context.Context, gitlabURL string, token string, fullPath string, settings gitprovider.RepositorySettings) error) *MockGitProjectProvider_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectExists provides a mock function for the type MockGitProjectProvider
func (_mock *MockGitProjectProvider) ProjectExists(ctx context.Context, gitlabURL string, token string, projectID string) (bool, error) {
	ret := _mock.Called(ctx, gitlabURL, token, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ProjectExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, gitlabURL, token, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, gitlabURL, token, projectID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, gitlabURL, token, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitProjectProvider_ProjectExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectExists'
type MockGitProjectProvider_ProjectExists_Call struct {
	*mock.Call
}

// ProjectExists is a helper method to define mock.On call
//   - ctx context.Context
//   - gitlabURL string
//   - token string
//   - projectID string
func (_e *MockGitProjectProvider_Expecter) ProjectExists(ctx interface{}, gitlabURL interface{}, token interface{}, projectID interface{}) *MockGitProjectProvider_ProjectExists_Call {
	return &MockGitProjectProvider_ProjectExists_Call{Call: _e.mock.On("ProjectExists", ctx, gitlabURL, token, projectID)}
}

func (_c *MockGitProjectProvider_ProjectExists_Call) Run(run func(ctx context.Context, gitlabURL string, token string, projectID string)) *MockGitProjectProvider_ProjectExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGitProjectProvider_ProjectExists_Call) Return(b bool, err error) *MockGitProjectProvider_ProjectExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGitProjectProvider_ProjectExists_Call) RunAndReturn(run func(ctx context.Context, gitlabURL string, token string, projectID string) (bool, error)) *MockGitProjectProvider_ProjectExists_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultBranch provides a mock function for the type MockGitProjectProvider
func (_mock *MockGitProjectProvider) SetDefaultBranch(ctx context.Context, githubURL string, token string, projectID string, branch string) error {
	ret := _mock.Called(ctx, githubURL, token, projectID, branch)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, githubURL, token, projectID, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitProjectProvider_SetDefaultBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultBranch'
type MockGitProjectProvider_SetDefaultBranch_Call struct {
	*mock.Call
}

// SetDefaultBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - githubURL string
//   - token string
//   - projectID string
//   - branch string
func (_e *MockGitProjectProvider_Expecter) SetDefaultBranch(ctx interface{}, githubURL interface{}, token interface{}, projectID interface{}, branch interface{}) *MockGitProjectProvider_SetDefaultBranch_Call {
	return &MockGitProjectProvider_SetDefaultBranch_Call{Call: _e.mock.On("SetDefaultBranch", ctx, githubURL, token, projectID, branch)}
}

func (_c *MockGitProjectProvider_SetDefaultBranch_Call) Run(run func(ctx context.Context, githubURL string, token string, projectID string, branch string)) *MockGitProjectProvider_SetDefaultBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitProjectProvider_SetDefaultBranch_Call) Return(err error) *MockGitProjectProvider_SetDefaultBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitProjectProvider_SetDefaultBranch_Call) RunAndReturn(run func(ctx context.Context, githubURL string, token string, projectID string, branch string) error) *MockGitProjectProvider_SetDefaultBranch_Call {
	_c.Call.Return(run)
	return _c
}
