// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-codebase-operator/v2/pkg/gitprovider"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitWebHookProvider creates a new instance of MockGitWebHookProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitWebHookProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitWebHookProvider {
	mock := &MockGitWebHookProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitWebHookProvider is an autogenerated mock type for the GitWebHookProvider type
type MockGitWebHookProvider struct {
	mock.Mock
}

type MockGitWebHookProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitWebHookProvider) EXPECT() *MockGitWebHookProvider_Expecter {
	return &MockGitWebHookProvider_Expecter{mock: &_m.Mock}
}

// CreateWebHook provides a mock function for the type MockGitWebHookProvider
func (_mock *MockGitWebHookProvider) CreateWebHook(ctx context.Context, gitProviderURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool) (*gitprovider.WebHook, error) {
	ret := _mock.Called(ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)

	if len(ret) == 0 {
		panic("no return value specified for CreateWebHook")
	}

	var r0 *gitprovider.WebHook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) (*gitprovider.WebHook, error)); ok {
		return returnFunc(ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) *gitprovider.WebHook); ok {
		r0 = returnFunc(ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitprovider.WebHook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, bool) error); ok {
		r1 = returnFunc(ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitWebHookProvider_CreateWebHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWebHook'
type MockGitWebHookProvider_CreateWebHook_Call struct {
	*mock.Call
}

// CreateWebHook is a helper method to define mock.On call
//   - ctx context.Context
//   - gitProviderURL string
//   - token string
//   - projectID string
//   - webHookSecret string
//   - webHookURL string
//   - skipTLS bool
func (_e *MockGitWebHookProvider_Expecter) CreateWebHook(ctx interface{}, gitProviderURL interface{}, token interface{}, projectID interface{}, webHookSecret interface{}, webHookURL interface{}, skipTLS interface{}) *MockGitWebHookProvider_CreateWebHook_Call {
	return &MockGitWebHookProvider_CreateWebHook_Call{Call: _e.mock.On("CreateWebHook", ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)}
}

func (_c *MockGitWebHookProvider_CreateWebHook_Call) Run(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool)) *MockGitWebHookProvider_CreateWebHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockGitWebHookProvider_CreateWebHook_Call) Return(webHook *gitprovider.WebHook, err error) *MockGitWebHookProvider_CreateWebHook_Call {
	_c.Call.Return(webHook, err)
	return _c
}

func (_c *MockGitWebHookProvider_CreateWebHook_Call) RunAndReturn(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool) (*gitprovider.WebHook, error)) *MockGitWebHookProvider_CreateWebHook_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWebHookIfNotExists provides a mock function for the type MockGitWebHookProvider
func (_mock *MockGitWebHookProvider) CreateWebHookIfNotExists(ctx context.Context, githubURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool) (*gitprovider.WebHook, error) {
	ret := _mock.Called(ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)

	if len(ret) == 0 {
		panic("no return value specified for CreateWebHookIfNotExists")
	}

	var r0 *gitprovider.WebHook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) (*gitprovider.WebHook, error)); ok {
		return returnFunc(ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) *gitprovider.WebHook); ok {
		r0 = returnFunc(ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitprovider.WebHook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, bool) error); ok {
		r1 = returnFunc(ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitWebHookProvider_CreateWebHookIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWebHookIfNotExists'
type MockGitWebHookProvider_CreateWebHookIfNotExists_Call struct {
	*mock.Call
}

// CreateWebHookIfNotExists is a helper method to define mock.On call
//   - ctx context.Context
//   - githubURL string
//   - token string
//   - projectID string
//   - webHookSecret string
//   - webHookURL string
//   - skipTLS bool
func (_e *MockGitWebHookProvider_Expecter) CreateWebHookIfNotExists(ctx interface{}, githubURL interface{}, token interface{}, projectID interface{}, webHookSecret interface{}, webHookURL interface{}, skipTLS interface{}) *MockGitWebHookProvider_CreateWebHookIfNotExists_Call {
	return &MockGitWebHookProvider_CreateWebHookIfNotExists_Call{Call: _e.mock.On("CreateWebHookIfNotExists", ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)}
}

func (_c *MockGitWebHookProvider_CreateWebHookIfNotExists_Call) Run(run func(ctx context.Context, githubURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool)) *MockGitWebHookProvider_CreateWebHookIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockGitWebHookProvider_CreateWebHookIfNotExists_Call) Return(webHook *gitprovider.WebHook, err error) *MockGitWebHookProvider_CreateWebHookIfNotExists_Call {
	_c.Call.Return(webHook, err)
	return _c
}

func (_c *MockGitWebHookProvider_CreateWebHookIfNotExists_Call) RunAndReturn(run func(ctx context.Context, githubURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool) (*gitprovider.WebHook, error)) *MockGitWebHookProvider_CreateWebHookIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWebHook provides a mock function for the type MockGitWebHookProvider
func (_mock *MockGitWebHookProvider) DeleteWebHook(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string) error {
	ret := _mock.Called(ctx, gitProviderURL, token, projectID, webHookRef)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWebHook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, gitProviderURL, token, projectID, webHookRef)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitWebHookProvider_DeleteWebHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWebHook'
type MockGitWebHookProvider_DeleteWebHook_Call struct {
	*mock.Call
}

// DeleteWebHook is a helper method to define mock.On call
//   - ctx context.Context
//   - gitProviderURL string
//   - token string
//   - projectID string
//   - webHookRef string
func (_e *MockGitWebHookProvider_Expecter) DeleteWebHook(ctx interface{}, gitProviderURL interface{}, token interface{}, projectID interface{}, webHookRef interface{}) *MockGitWebHookProvider_DeleteWebHook_Call {
	return &MockGitWebHookProvider_DeleteWebHook_Call{Call: _e.mock.On("DeleteWebHook", ctx, gitProviderURL, token, projectID, webHookRef)}
}

func (_c *MockGitWebHookProvider_DeleteWebHook_Call) Run(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string)) *MockGitWebHookProvider_DeleteWebHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitWebHookProvider_DeleteWebHook_Call) Return(err error) *MockGitWebHookProvider_DeleteWebHook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitWebHookProvider_DeleteWebHook_Call) RunAndReturn(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string) error) *MockGitWebHookProvider_DeleteWebHook_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebHook provides a mock function for the type MockGitWebHookProvider
func (_mock *MockGitWebHookProvider) GetWebHook(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string) (*gitprovider.WebHook, error) {
	ret := _mock.Called(ctx, gitProviderURL, token, projectID, webHookRef)

	if len(ret) == 0 {
		panic("no return value specified for GetWebHook")
	}

	var r0 *gitprovider.WebHook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*gitprovider.WebHook, error)); ok {
		return returnFunc(ctx, gitProviderURL, token, projectID, webHookRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *gitprovider.WebHook); ok {
		r0 = returnFunc(ctx, gitProviderURL, token, projectID, webHookRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitprovider.WebHook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, gitProviderURL, token, projectID, webHookRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitWebHookProvider_GetWebHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebHook'
type MockGitWebHookProvider_GetWebHook_Call struct {
	*mock.Call
}

// GetWebHook is a helper method to define mock.On call
//   - ctx context.Context
//   - gitProviderURL string
//   - token string
//   - projectID string
//   - webHookRef string
func (_e *MockGitWebHookProvider_Expecter) GetWebHook(ctx interface{}, gitProviderURL interface{}, token interface{}, projectID interface{}, webHookRef interface{}) *MockGitWebHookProvider_GetWebHook_Call {
	return &MockGitWebHookProvider_GetWebHook_Call{Call: _e.mock.On("GetWebHook", ctx, gitProviderURL, token, projectID, webHookRef)}
}

func (_c *MockGitWebHookProvider_GetWebHook_Call) Run(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string)) *MockGitWebHookProvider_GetWebHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitWebHookProvider_GetWebHook_Call) Return(webHook *gitprovider.WebHook, err error) *MockGitWebHookProvider_GetWebHook_Call {
	_c.Call.Return(webHook, err)
	return _c
}

func (_c *MockGitWebHookProvider_GetWebHook_Call) RunAndReturn(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string) (*gitprovider.WebHook, error)) *MockGitWebHookProvider_GetWebHook_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebHooks provides a mock function for the type MockGitWebHookProvider
func (_mock *MockGitWebHookProvider) GetWebHooks(ctx context.Context, githubURL string, token string, projectID string) ([]*gitprovider.WebHook, error) {
	ret := _mock.Called(ctx, githubURL, token, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetWebHooks")
	}

	var r0 []*gitprovider.WebHook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*gitprovider.WebHook, error)); ok {
		return returnFunc(ctx, githubURL, token, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []*gitprovider.WebHook); ok {
		r0 = returnFunc(ctx, githubURL, token, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitprovider.WebHook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, githubURL, token, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitWebHookProvider_GetWebHooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebHooks'
type MockGitWebHookProvider_GetWebHooks_Call struct {
	*mock.Call
}

// GetWebHooks is a helper method to define mock.On call
//   - ctx context.Context
//   - githubURL string
//   - token string
//   - projectID string
func (_e *MockGitWebHookProvider_Expecter) GetWebHooks(ctx interface{}, githubURL interface{}, token interface{}, projectID interface{}) *MockGitWebHookProvider_GetWebHooks_Call {
	return &MockGitWebHookProvider_GetWebHooks_Call{Call: _e.mock.On("GetWebHooks", ctx, githubURL, token, projectID)}
}

func (_c *MockGitWebHookProvider_GetWebHooks_Call) Run(run func(ctx context.Context, githubURL string, token string, projectID string)) *MockGitWebHookProvider_GetWebHooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGitWebHookProvider_GetWebHooks_Call) Return(webHooks []*gitprovider.WebHook, err error) *MockGitWebHookProvider_GetWebHooks_Call {
	_c.Call.Return(webHooks, err)
	return _c
}

func (_c *MockGitWebHookProvider_GetWebHooks_Call) RunAndReturn(run func(ctx context.Context, githubURL string, token string, projectID string) ([]*gitprovider.WebHook, error)) *MockGitWebHookProvider_GetWebHooks_Call {
	_c.Call.Return(run)
	return _c
}
