// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-codebase-operator/v2/pkg/gitprovider"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitProvider creates a new instance of MockGitProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitProvider {
	mock := &MockGitProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitProvider is an autogenerated mock type for the GitProvider type
type MockGitProvider struct {
	mock.Mock
}

type MockGitProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitProvider) EXPECT() *MockGitProvider_Expecter {
	return &MockGitProvider_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function for the type MockGitProvider
func (_mock *MockGitProvider) CreateProject(ctx context.Context, gitlabURL string, token string, fullPath string, settings gitprovider.RepositorySettings) error {
	ret := _mock.Called(ctx, gitlabURL, token, fullPath, settings)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, gitprovider.RepositorySettings) error); ok {
		r0 = returnFunc(ctx, gitlabURL, token, fullPath, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitProvider_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockGitProvider_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - gitlabURL string
//   - token string
//   - fullPath string
//   - settings gitprovider.RepositorySettings
func (_e *MockGitProvider_Expecter) CreateProject(ctx interface{}, gitlabURL interface{}, token interface{}, fullPath interface{}, settings interface{}) *MockGitProvider_CreateProject_Call {
	return &MockGitProvider_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, gitlabURL, token, fullPath, settings)}
}

func (_c *MockGitProvider_CreateProject_Call) Run(run func(ctx context.Context, gitlabURL string, token string, fullPath string, settings gitprovider.RepositorySettings)) *MockGitProvider_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 gitprovider.RepositorySettings
		if args[4] != nil {
			arg4 = args[4].(gitprovider.RepositorySettings)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitProvider_CreateProject_Call) Return(err error) *MockGitProvider_CreateProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitProvider_CreateProject_Call) RunAndReturn(run func(ctx context.Context, gitlabURL string, token string, fullPath string, settings gitprovider.RepositorySettings) error) *MockGitProvider_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWebHook provides a mock function for the type MockGitProvider
func (_mock *MockGitProvider) CreateWebHook(ctx context.Context, gitProviderURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool) (*gitprovider.WebHook, error) {
	ret := _mock.Called(ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)

	if len(ret) == 0 {
		panic("no return value specified for CreateWebHook")
	}

	var r0 *gitprovider.WebHook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) (*gitprovider.WebHook, error)); ok {
		return returnFunc(ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) *gitprovider.WebHook); ok {
		r0 = returnFunc(ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitprovider.WebHook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, bool) error); ok {
		r1 = returnFunc(ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitProvider_CreateWebHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWebHook'
type MockGitProvider_CreateWebHook_Call struct {
	*mock.Call
}

// CreateWebHook is a helper method to define mock.On call
//   - ctx context.Context
//   - gitProviderURL string
//   - token string
//   - projectID string
//   - webHookSecret string
//   - webHookURL string
//   - skipTLS bool
func (_e *MockGitProvider_Expecter) CreateWebHook(ctx interface{}, gitProviderURL interface{}, token interface{}, projectID interface{}, webHookSecret interface{}, webHookURL interface{}, skipTLS interface{}) *MockGitProvider_CreateWebHook_Call {
	return &MockGitProvider_CreateWebHook_Call{Call: _e.mock.On("CreateWebHook", ctx, gitProviderURL, token, projectID, webHookSecret, webHookURL, skipTLS)}
}

func (_c *MockGitProvider_CreateWebHook_Call) Run(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool)) *MockGitProvider_CreateWebHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockGitProvider_CreateWebHook_Call) Return(webHook *gitprovider.WebHook, err error) *MockGitProvider_CreateWebHook_Call {
	_c.Call.Return(webHook, err)
	return _c
}

func (_c *MockGitProvider_CreateWebHook_Call) RunAndReturn(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool) (*gitprovider.WebHook, error)) *MockGitProvider_CreateWebHook_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWebHookIfNotExists provides a mock function for the type MockGitProvider
func (_mock *MockGitProvider) CreateWebHookIfNotExists(ctx context.Context, githubURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool) (*gitprovider.WebHook, error) {
	ret := _mock.Called(ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)

	if len(ret) == 0 {
		panic("no return value specified for CreateWebHookIfNotExists")
	}

	var r0 *gitprovider.WebHook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) (*gitprovider.WebHook, error)); ok {
		return returnFunc(ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) *gitprovider.WebHook); ok {
		r0 = returnFunc(ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitprovider.WebHook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, bool) error); ok {
		r1 = returnFunc(ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitProvider_CreateWebHookIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWebHookIfNotExists'
type MockGitProvider_CreateWebHookIfNotExists_Call struct {
	*mock.Call
}

// CreateWebHookIfNotExists is a helper method to define mock.On call
//   - ctx context.Context
//   - githubURL string
//   - token string
//   - projectID string
//   - webHookSecret string
//   - webHookURL string
//   - skipTLS bool
func (_e *MockGitProvider_Expecter) CreateWebHookIfNotExists(ctx interface{}, githubURL interface{}, token interface{}, projectID interface{}, webHookSecret interface{}, webHookURL interface{}, skipTLS interface{}) *MockGitProvider_CreateWebHookIfNotExists_Call {
	return &MockGitProvider_CreateWebHookIfNotExists_Call{Call: _e.mock.On("CreateWebHookIfNotExists", ctx, githubURL, token, projectID, webHookSecret, webHookURL, skipTLS)}
}

func (_c *MockGitProvider_CreateWebHookIfNotExists_Call) Run(run func(ctx context.Context, githubURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool)) *MockGitProvider_CreateWebHookIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockGitProvider_CreateWebHookIfNotExists_Call) Return(webHook *gitprovider.WebHook, err error) *MockGitProvider_CreateWebHookIfNotExists_Call {
	_c.Call.Return(webHook, err)
	return _c
}

func (_c *MockGitProvider_CreateWebHookIfNotExists_Call) RunAndReturn(run func(ctx context.Context, githubURL string, token string, projectID string, webHookSecret string, webHookURL string, skipTLS bool) (*gitprovider.WebHook, error)) *MockGitProvider_CreateWebHookIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWebHook provides a mock function for the type MockGitProvider
func (_mock *MockGitProvider) DeleteWebHook(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string) error {
	ret := _mock.Called(ctx, gitProviderURL, token, projectID, webHookRef)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWebHook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, gitProviderURL, token, projectID, webHookRef)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitProvider_DeleteWebHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWebHook'
type MockGitProvider_DeleteWebHook_Call struct {
	*mock.Call
}

// DeleteWebHook is a helper method to define mock.On call
//   - ctx context.Context
//   - gitProviderURL string
//   - token string
//   - projectID string
//   - webHookRef string
func (_e *MockGitProvider_Expecter) DeleteWebHook(ctx interface{}, gitProviderURL interface{}, token interface{}, projectID interface{}, webHookRef interface{}) *MockGitProvider_DeleteWebHook_Call {
	return &MockGitProvider_DeleteWebHook_Call{Call: _e.mock.On("DeleteWebHook", ctx, gitProviderURL, token, projectID, webHookRef)}
}

func (_c *MockGitProvider_DeleteWebHook_Call) Run(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string)) *MockGitProvider_DeleteWebHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitProvider_DeleteWebHook_Call) Return(err error) *MockGitProvider_DeleteWebHook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitProvider_DeleteWebHook_Call) RunAndReturn(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string) error) *MockGitProvider_DeleteWebHook_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebHook provides a mock function for the type MockGitProvider
func (_mock *MockGitProvider) GetWebHook(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string) (*gitprovider.WebHook, error) {
	ret := _mock.Called(ctx, gitProviderURL, token, projectID, webHookRef)

	if len(ret) == 0 {
		panic("no return value specified for GetWebHook")
	}

	var r0 *gitprovider.WebHook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*gitprovider.WebHook, error)); ok {
		return returnFunc(ctx, gitProviderURL, token, projectID, webHookRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *gitprovider.WebHook); ok {
		r0 = returnFunc(ctx, gitProviderURL, token, projectID, webHookRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitprovider.WebHook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, gitProviderURL, token, projectID, webHookRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitProvider_GetWebHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebHook'
type MockGitProvider_GetWebHook_Call struct {
	*mock.Call
}

// GetWebHook is a helper method to define mock.On call
//   - ctx context.Context
//   - gitProviderURL string
//   - token string
//   - projectID string
//   - webHookRef string
func (_e *MockGitProvider_Expecter) GetWebHook(ctx interface{}, gitProviderURL interface{}, token interface{}, projectID interface{}, webHookRef interface{}) *MockGitProvider_GetWebHook_Call {
	return &MockGitProvider_GetWebHook_Call{Call: _e.mock.On("GetWebHook", ctx, gitProviderURL, token, projectID, webHookRef)}
}

func (_c *MockGitProvider_GetWebHook_Call) Run(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string)) *MockGitProvider_GetWebHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitProvider_GetWebHook_Call) Return(webHook *gitprovider.WebHook, err error) *MockGitProvider_GetWebHook_Call {
	_c.Call.Return(webHook, err)
	return _c
}

func (_c *MockGitProvider_GetWebHook_Call) RunAndReturn(run func(ctx context.Context, gitProviderURL string, token string, projectID string, webHookRef string) (*gitprovider.WebHook, error)) *MockGitProvider_GetWebHook_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebHooks provides a mock function for the type MockGitProvider
func (_mock *MockGitProvider) GetWebHooks(ctx context.Context, githubURL string, token string, projectID string) ([]*gitprovider.WebHook, error) {
	ret := _mock.Called(ctx, githubURL, token, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetWebHooks")
	}

	var r0 []*gitprovider.WebHook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*gitprovider.WebHook, error)); ok {
		return returnFunc(ctx, githubURL, token, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []*gitprovider.WebHook); ok {
		r0 = returnFunc(ctx, githubURL, token, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitprovider.WebHook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, githubURL, token, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitProvider_GetWebHooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebHooks'
type MockGitProvider_GetWebHooks_Call struct {
	*mock.Call
}

// GetWebHooks is a helper method to define mock.On call
//   - ctx context.Context
//   - githubURL string
//   - token string
//   - projectID string
func (_e *MockGitProvider_Expecter) GetWebHooks(ctx interface{}, githubURL interface{}, token interface{}, projectID interface{}) *MockGitProvider_GetWebHooks_Call {
	return &MockGitProvider_GetWebHooks_Call{Call: _e.mock.On("GetWebHooks", ctx, githubURL, token, projectID)}
}

func (_c *MockGitProvider_GetWebHooks_Call) Run(run func(ctx context.Context, githubURL string, token string, projectID string)) *MockGitProvider_GetWebHooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGitProvider_GetWebHooks_Call) Return(webHooks []*gitprovider.WebHook, err error) *MockGitProvider_GetWebHooks_Call {
	_c.Call.Return(webHooks, err)
	return _c
}

func (_c *MockGitProvider_GetWebHooks_Call) RunAndReturn(run func(ctx context.Context, githubURL string, token string, projectID string) ([]*gitprovider.WebHook, error)) *MockGitProvider_GetWebHooks_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectExists provides a mock function for the type MockGitProvider
func (_mock *MockGitProvider) ProjectExists(ctx context.Context, gitlabURL string, token string, projectID string) (bool, error) {
	ret := _mock.Called(ctx, gitlabURL, token, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ProjectExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, gitlabURL, token, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, gitlabURL, token, projectID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, gitlabURL, token, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitProvider_ProjectExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectExists'
type MockGitProvider_ProjectExists_Call struct {
	*mock.Call
}

// ProjectExists is a helper method to define mock.On call
//   - ctx context.Context
//   - gitlabURL string
//   - token string
//   - projectID string
func (_e *MockGitProvider_Expecter) ProjectExists(ctx interface{}, gitlabURL interface{}, token interface{}, projectID interface{}) *MockGitProvider_ProjectExists_Call {
	return &MockGitProvider_ProjectExists_Call{Call: _e.mock.On("ProjectExists", ctx, gitlabURL, token, projectID)}
}

func (_c *MockGitProvider_ProjectExists_Call) Run(run func(ctx context.Context, gitlabURL string, token string, projectID string)) *MockGitProvider_ProjectExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGitProvider_ProjectExists_Call) Return(b bool, err error) *MockGitProvider_ProjectExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGitProvider_ProjectExists_Call) RunAndReturn(run func(ctx context.Context, gitlabURL string, token string, projectID string) (bool, error)) *MockGitProvider_ProjectExists_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultBranch provides a mock function for the type MockGitProvider
func (_mock *MockGitProvider) SetDefaultBranch(ctx context.Context, githubURL string, token string, projectID string, branch string) error {
	ret := _mock.Called(ctx, githubURL, token, projectID, branch)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, githubURL, token, projectID, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitProvider_SetDefaultBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultBranch'
type MockGitProvider_SetDefaultBranch_Call struct {
	*mock.Call
}

// SetDefaultBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - githubURL string
//   - token string
//   - projectID string
//   - branch string
func (_e *MockGitProvider_Expecter) SetDefaultBranch(ctx interface{}, githubURL interface{}, token interface{}, projectID interface{}, branch interface{}) *MockGitProvider_SetDefaultBranch_Call {
	return &MockGitProvider_SetDefaultBranch_Call{Call: _e.mock.On("SetDefaultBranch", ctx, githubURL, token, projectID, branch)}
}

func (_c *MockGitProvider_SetDefaultBranch_Call) Run(run func(ctx context.Context, githubURL string, token string, projectID string, branch string)) *MockGitProvider_SetDefaultBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitProvider_SetDefaultBranch_Call) Return(err error) *MockGitProvider_SetDefaultBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitProvider_SetDefaultBranch_Call) RunAndReturn(run func(ctx context.Context, githubURL string, token string, projectID string, branch string) error) *MockGitProvider_SetDefaultBranch_Call {
	_c.Call.Return(run)
	return _c
}
