// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/epam/edp-codebase-operator/v2/api/v1"
)

// CDStageDeployHandler is an autogenerated mock type for the CDStageDeployHandler type
type CDStageDeployHandler struct {
	mock.Mock
}

// ServeRequest provides a mock function with given fields: ctx, stageDeploy
func (_m *CDStageDeployHandler) ServeRequest(ctx context.Context, stageDeploy *v1.CDStageDeploy) error {
	ret := _m.Called(ctx, stageDeploy)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CDStageDeploy) error); ok {
		r0 = rf(ctx, stageDeploy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCDStageDeployHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewCDStageDeployHandler creates a new instance of CDStageDeployHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCDStageDeployHandler(t mockConstructorTestingTNewCDStageDeployHandler) *CDStageDeployHandler {
	mock := &CDStageDeployHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
