apiVersion: v2
description: A Helm chart for EDP Codebase Operator
home: https://epam.github.io/edp-install/
name: codebase-operator
type: application
version: 2.23.0-SNAPSHOT
appVersion: 2.23.0-SNAPSHOT
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - edp
  - codebase
  - operator
  - pipelines
  - jira
  - ci
  - cd
  - docker
  - image
  - promote
  - git
  - gerrit
  - github
  - gitlab
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-codebase-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: codebase-operator:2.22.0
      image: epamedp/codebase-operator:2.22.0
    - name: alpine:3.18.6
      image: alpine:3.18.6
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: CDStageDeploy
      version: v2.edp.epam.com/v1
      name: cdstagedeploy
      displayName: CDStageDeploy
      description: Stage deploy configuration for CD
    - kind: Codebase
      version: v2.edp.epam.com/v1
      name: codebase
      displayName: Codebase
      description: Creates an application in the admin console and starts CI pipeline
    - kind: CodebaseBranch
      version: v2.edp.epam.com/v1
      name: codebasebranch
      displayName: CodebaseBranch
      description: Creates a branch for an application
    - kind: CodebaseImageStream
      version: v2.edp.epam.com/v1
      name: codebaseimagestream
      displayName: CodebaseImageStream
      description: Creates a link to an images
    - kind: GitServer
      version: v2.edp.epam.com/v1
      name: gitserver
      displayName: GitServer
      description: Communicates with Git server
    - kind: JiraIssueMetadata
      version: v2.edp.epam.com/v1
      name: jiraissuemetadata
      displayName: JiraIssueMetadata
      description: Creates Jira metadata
    - kind: JiraServer
      version: v2.edp.epam.com/v1
      name: jiraserver
      displayName: JiraServer
      description: Operates with Jira server
  artifacthub.io/crdsExamples: |
    - apiVersion: v2.edp.epam.com/v1
      kind: Codebase
      metadata:
        name: javascript-deploy-edp
      spec:
        buildTool: NPM
        ciTool: tekton
        commitMessagePattern: null
        defaultBranch: branch/dev-1
        deploymentScript: helm-chart
        description: null
        emptyProject: false
        framework: react
        gitServer: gerrit
        gitUrlPath: null
        jiraIssueMetadataPayload: null
        lang: JavaScript
        repository: null
        strategy: create
        testReportFramework: null
        ticketNamePattern: null
        type: application
        versioning:
          startFrom: 1.2.3-SNAPSHOT
          type: edp
    - apiVersion: v2.edp.epam.com/v1
      kind: CodebaseBranch
      metadata:
        name: javascript-deploy-edp-branch-dev-1
      spec:
        branchName: branch/dev-1
        codebaseName: javascript-deploy-edp
        fromCommit: 'latest'
        release: false
        releaseJobParams: null
        version: 1.2.3-SNAPSHOT
    - apiVersion: v2.edp.epam.com/v1
      kind: CodebaseImageStream
      metadata:
        name: javascript-deploy-edp-branch-dev-1
      spec:
        codebase: javascript-deploy-edp
        imageName: >-
          epamedp/javascript-deploy-edp
        tags:
          - created: '2022-05-25T08:57:12'
            name: branch/dev-1-0.0.1-snapshot-1
    - apiVersion: v2.edp.epam.com/v1
      kind: GitServer
      metadata:
        name: gerrit
      spec:
        gitHost: gerrit.edp-dev
        gitUser: git
        httpsPort: 443
        nameSshKeySecret: gerrit-ciuser-sshkey
        sshPort: 30002
    - apiVersion: v2.edp.epam.com/v1
      kind: JiraServer
      metadata:
        name: jiraserver
      spec:
        apiUrl: https://jiraeu-api.test.com
        credentialName: test-jira-user
        rootUrl: https://jiraeu.test.com
    - apiVersion: v2.edp.epam.com/v1alpha1
      kind: Template
      metadata:
        name: my-template
      spec:
        displayName: MyTemplate
        buildTool: tool
        type: application
        framework: framework
        language: programming-language
        description: description
        category: category
        # Icon defines the image that UIs can use to represent this package.
        icon:
          - base64data: <base64-encoded-data>
            mediatype: image/svg+xml
        keywords:
          - keyword1
          - keyword2
        maintainers:
          - name: team
            email: team@example.com
        source: https://github.com/epam/edp-codebase-operator
        version: 1.0.1
        minEDPVersion: 2.0.0
        maturity: stable
  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
