// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-codebase-operator/v2/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCodebaseHandler creates a new instance of MockCodebaseHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodebaseHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodebaseHandler {
	mock := &MockCodebaseHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCodebaseHandler is an autogenerated mock type for the CodebaseHandler type
type MockCodebaseHandler struct {
	mock.Mock
}

type MockCodebaseHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodebaseHandler) EXPECT() *MockCodebaseHandler_Expecter {
	return &MockCodebaseHandler_Expecter{mock: &_m.Mock}
}

// ServeRequest provides a mock function for the type MockCodebaseHandler
func (_mock *MockCodebaseHandler) ServeRequest(context1 context.Context, codebase *v1.Codebase) error {
	ret := _mock.Called(context1, codebase)

	if len(ret) == 0 {
		panic("no return value specified for ServeRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Codebase) error); ok {
		r0 = returnFunc(context1, codebase)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCodebaseHandler_ServeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeRequest'
type MockCodebaseHandler_ServeRequest_Call struct {
	*mock.Call
}

// ServeRequest is a helper method to define mock.On call
//   - context1 context.Context
//   - codebase *v1.Codebase
func (_e *MockCodebaseHandler_Expecter) ServeRequest(context1 interface{}, codebase interface{}) *MockCodebaseHandler_ServeRequest_Call {
	return &MockCodebaseHandler_ServeRequest_Call{Call: _e.mock.On("ServeRequest", context1, codebase)}
}

func (_c *MockCodebaseHandler_ServeRequest_Call) Run(run func(context1 context.Context, codebase *v1.Codebase)) *MockCodebaseHandler_ServeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.Codebase
		if args[1] != nil {
			arg1 = args[1].(*v1.Codebase)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCodebaseHandler_ServeRequest_Call) Return(err error) *MockCodebaseHandler_ServeRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCodebaseHandler_ServeRequest_Call) RunAndReturn(run func(context1 context.Context, codebase *v1.Codebase) error) *MockCodebaseHandler_ServeRequest_Call {
	_c.Call.Return(run)
	return _c
}
