// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/epam/edp-codebase-operator/v2/pkg/client/jira"
	"github.com/epam/edp-codebase-operator/v2/pkg/client/jira/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientFactory creates a new instance of MockClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientFactory {
	mock := &MockClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientFactory is an autogenerated mock type for the ClientFactory type
type MockClientFactory struct {
	mock.Mock
}

type MockClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientFactory) EXPECT() *MockClientFactory_Expecter {
	return &MockClientFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockClientFactory
func (_mock *MockClientFactory) New(jira1 dto.JiraServer) (jira.Client, error) {
	ret := _mock.Called(jira1)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 jira.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(dto.JiraServer) (jira.Client, error)); ok {
		return returnFunc(jira1)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.JiraServer) jira.Client); ok {
		r0 = returnFunc(jira1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jira.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dto.JiraServer) error); ok {
		r1 = returnFunc(jira1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockClientFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - jira1 dto.JiraServer
func (_e *MockClientFactory_Expecter) New(jira1 interface{}) *MockClientFactory_New_Call {
	return &MockClientFactory_New_Call{Call: _e.mock.On("New", jira1)}
}

func (_c *MockClientFactory_New_Call) Run(run func(jira1 dto.JiraServer)) *MockClientFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.JiraServer
		if args[0] != nil {
			arg0 = args[0].(dto.JiraServer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientFactory_New_Call) Return(client jira.Client, err error) *MockClientFactory_New_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientFactory_New_Call) RunAndReturn(run func(jira1 dto.JiraServer) (jira.Client, error)) *MockClientFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
