// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/andygrunwald/go-jira"
	jira0 "github.com/epam/edp-codebase-operator/v2/pkg/client/jira"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// ApplyTagsToIssue provides a mock function for the type MockClient
func (_mock *MockClient) ApplyTagsToIssue(issue string, tags map[string]interface{}) error {
	ret := _mock.Called(issue, tags)

	if len(ret) == 0 {
		panic("no return value specified for ApplyTagsToIssue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = returnFunc(issue, tags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ApplyTagsToIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyTagsToIssue'
type MockClient_ApplyTagsToIssue_Call struct {
	*mock.Call
}

// ApplyTagsToIssue is a helper method to define mock.On call
//   - issue string
//   - tags map[string]interface{}
func (_e *MockClient_Expecter) ApplyTagsToIssue(issue interface{}, tags interface{}) *MockClient_ApplyTagsToIssue_Call {
	return &MockClient_ApplyTagsToIssue_Call{Call: _e.mock.On("ApplyTagsToIssue", issue, tags)}
}

func (_c *MockClient_ApplyTagsToIssue_Call) Run(run func(issue string, tags map[string]interface{})) *MockClient_ApplyTagsToIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ApplyTagsToIssue_Call) Return(err error) *MockClient_ApplyTagsToIssue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ApplyTagsToIssue_Call) RunAndReturn(run func(issue string, tags map[string]interface{}) error) *MockClient_ApplyTagsToIssue_Call {
	_c.Call.Return(run)
	return _c
}

// Connected provides a mock function for the type MockClient
func (_mock *MockClient) Connected() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connected")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Connected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connected'
type MockClient_Connected_Call struct {
	*mock.Call
}

// Connected is a helper method to define mock.On call
func (_e *MockClient_Expecter) Connected() *MockClient_Connected_Call {
	return &MockClient_Connected_Call{Call: _e.mock.On("Connected")}
}

func (_c *MockClient_Connected_Call) Run(run func()) *MockClient_Connected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Connected_Call) Return(b bool, err error) *MockClient_Connected_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockClient_Connected_Call) RunAndReturn(run func() (bool, error)) *MockClient_Connected_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComponentValue provides a mock function for the type MockClient
func (_mock *MockClient) CreateComponentValue(ctx context.Context, projectId int, componentName string) error {
	ret := _mock.Called(ctx, projectId, componentName)

	if len(ret) == 0 {
		panic("no return value specified for CreateComponentValue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, projectId, componentName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateComponentValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComponentValue'
type MockClient_CreateComponentValue_Call struct {
	*mock.Call
}

// CreateComponentValue is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId int
//   - componentName string
func (_e *MockClient_Expecter) CreateComponentValue(ctx interface{}, projectId interface{}, componentName interface{}) *MockClient_CreateComponentValue_Call {
	return &MockClient_CreateComponentValue_Call{Call: _e.mock.On("CreateComponentValue", ctx, projectId, componentName)}
}

func (_c *MockClient_CreateComponentValue_Call) Run(run func(ctx context.Context, projectId int, componentName string)) *MockClient_CreateComponentValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CreateComponentValue_Call) Return(err error) *MockClient_CreateComponentValue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateComponentValue_Call) RunAndReturn(run func(ctx context.Context, projectId int, componentName string) error) *MockClient_CreateComponentValue_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFixVersionValue provides a mock function for the type MockClient
func (_mock *MockClient) CreateFixVersionValue(ctx context.Context, projectId int, versionName string) error {
	ret := _mock.Called(ctx, projectId, versionName)

	if len(ret) == 0 {
		panic("no return value specified for CreateFixVersionValue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, projectId, versionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateFixVersionValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFixVersionValue'
type MockClient_CreateFixVersionValue_Call struct {
	*mock.Call
}

// CreateFixVersionValue is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId int
//   - versionName string
func (_e *MockClient_Expecter) CreateFixVersionValue(ctx interface{}, projectId interface{}, versionName interface{}) *MockClient_CreateFixVersionValue_Call {
	return &MockClient_CreateFixVersionValue_Call{Call: _e.mock.On("CreateFixVersionValue", ctx, projectId, versionName)}
}

func (_c *MockClient_CreateFixVersionValue_Call) Run(run func(ctx context.Context, projectId int, versionName string)) *MockClient_CreateFixVersionValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CreateFixVersionValue_Call) Return(err error) *MockClient_CreateFixVersionValue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateFixVersionValue_Call) RunAndReturn(run func(ctx context.Context, projectId int, versionName string) error) *MockClient_CreateFixVersionValue_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIssueLink provides a mock function for the type MockClient
func (_mock *MockClient) CreateIssueLink(issueId string, title string, url string) error {
	ret := _mock.Called(issueId, title, url)

	if len(ret) == 0 {
		panic("no return value specified for CreateIssueLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(issueId, title, url)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateIssueLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIssueLink'
type MockClient_CreateIssueLink_Call struct {
	*mock.Call
}

// CreateIssueLink is a helper method to define mock.On call
//   - issueId string
//   - title string
//   - url string
func (_e *MockClient_Expecter) CreateIssueLink(issueId interface{}, title interface{}, url interface{}) *MockClient_CreateIssueLink_Call {
	return &MockClient_CreateIssueLink_Call{Call: _e.mock.On("CreateIssueLink", issueId, title, url)}
}

func (_c *MockClient_CreateIssueLink_Call) Run(run func(issueId string, title string, url string)) *MockClient_CreateIssueLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CreateIssueLink_Call) Return(err error) *MockClient_CreateIssueLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateIssueLink_Call) RunAndReturn(run func(issueId string, title string, url string) error) *MockClient_CreateIssueLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssue provides a mock function for the type MockClient
func (_mock *MockClient) GetIssue(ctx context.Context, issueId string) (*jira.Issue, error) {
	ret := _mock.Called(ctx, issueId)

	if len(ret) == 0 {
		panic("no return value specified for GetIssue")
	}

	var r0 *jira.Issue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*jira.Issue, error)); ok {
		return returnFunc(ctx, issueId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *jira.Issue); ok {
		r0 = returnFunc(ctx, issueId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jira.Issue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, issueId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssue'
type MockClient_GetIssue_Call struct {
	*mock.Call
}

// GetIssue is a helper method to define mock.On call
//   - ctx context.Context
//   - issueId string
func (_e *MockClient_Expecter) GetIssue(ctx interface{}, issueId interface{}) *MockClient_GetIssue_Call {
	return &MockClient_GetIssue_Call{Call: _e.mock.On("GetIssue", ctx, issueId)}
}

func (_c *MockClient_GetIssue_Call) Run(run func(ctx context.Context, issueId string)) *MockClient_GetIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetIssue_Call) Return(issue *jira.Issue, err error) *MockClient_GetIssue_Call {
	_c.Call.Return(issue, err)
	return _c
}

func (_c *MockClient_GetIssue_Call) RunAndReturn(run func(ctx context.Context, issueId string) (*jira.Issue, error)) *MockClient_GetIssue_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssueTypeMeta provides a mock function for the type MockClient
func (_mock *MockClient) GetIssueTypeMeta(ctx context.Context, projectID string, issueTypeID string) (map[string]jira0.IssueTypeMeta, error) {
	ret := _mock.Called(ctx, projectID, issueTypeID)

	if len(ret) == 0 {
		panic("no return value specified for GetIssueTypeMeta")
	}

	var r0 map[string]jira0.IssueTypeMeta
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string]jira0.IssueTypeMeta, error)); ok {
		return returnFunc(ctx, projectID, issueTypeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string]jira0.IssueTypeMeta); ok {
		r0 = returnFunc(ctx, projectID, issueTypeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]jira0.IssueTypeMeta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, issueTypeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetIssueTypeMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssueTypeMeta'
type MockClient_GetIssueTypeMeta_Call struct {
	*mock.Call
}

// GetIssueTypeMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - issueTypeID string
func (_e *MockClient_Expecter) GetIssueTypeMeta(ctx interface{}, projectID interface{}, issueTypeID interface{}) *MockClient_GetIssueTypeMeta_Call {
	return &MockClient_GetIssueTypeMeta_Call{Call: _e.mock.On("GetIssueTypeMeta", ctx, projectID, issueTypeID)}
}

func (_c *MockClient_GetIssueTypeMeta_Call) Run(run func(ctx context.Context, projectID string, issueTypeID string)) *MockClient_GetIssueTypeMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetIssueTypeMeta_Call) Return(stringToIssueTypeMeta map[string]jira0.IssueTypeMeta, err error) *MockClient_GetIssueTypeMeta_Call {
	_c.Call.Return(stringToIssueTypeMeta, err)
	return _c
}

func (_c *MockClient_GetIssueTypeMeta_Call) RunAndReturn(run func(ctx context.Context, projectID string, issueTypeID string) (map[string]jira0.IssueTypeMeta, error)) *MockClient_GetIssueTypeMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectInfo provides a mock function for the type MockClient
func (_mock *MockClient) GetProjectInfo(issueId string) (*jira.Project, error) {
	ret := _mock.Called(issueId)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectInfo")
	}

	var r0 *jira.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jira.Project, error)); ok {
		return returnFunc(issueId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jira.Project); ok {
		r0 = returnFunc(issueId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jira.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(issueId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetProjectInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectInfo'
type MockClient_GetProjectInfo_Call struct {
	*mock.Call
}

// GetProjectInfo is a helper method to define mock.On call
//   - issueId string
func (_e *MockClient_Expecter) GetProjectInfo(issueId interface{}) *MockClient_GetProjectInfo_Call {
	return &MockClient_GetProjectInfo_Call{Call: _e.mock.On("GetProjectInfo", issueId)}
}

func (_c *MockClient_GetProjectInfo_Call) Run(run func(issueId string)) *MockClient_GetProjectInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetProjectInfo_Call) Return(project *jira.Project, err error) *MockClient_GetProjectInfo_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockClient_GetProjectInfo_Call) RunAndReturn(run func(issueId string) (*jira.Project, error)) *MockClient_GetProjectInfo_Call {
	_c.Call.Return(run)
	return _c
}
