// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/go-logr/logr"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CheckProjectExist provides a mock function for the type MockClient
func (_mock *MockClient) CheckProjectExist(port int32, sshPrivateKey string, host string, user string, appName string, logger logr.Logger) (bool, error) {
	ret := _mock.Called(port, sshPrivateKey, host, user, appName, logger)

	if len(ret) == 0 {
		panic("no return value specified for CheckProjectExist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int32, string, string, string, string, logr.Logger) (bool, error)); ok {
		return returnFunc(port, sshPrivateKey, host, user, appName, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(int32, string, string, string, string, logr.Logger) bool); ok {
		r0 = returnFunc(port, sshPrivateKey, host, user, appName, logger)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(int32, string, string, string, string, logr.Logger) error); ok {
		r1 = returnFunc(port, sshPrivateKey, host, user, appName, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CheckProjectExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckProjectExist'
type MockClient_CheckProjectExist_Call struct {
	*mock.Call
}

// CheckProjectExist is a helper method to define mock.On call
//   - port int32
//   - sshPrivateKey string
//   - host string
//   - user string
//   - appName string
//   - logger logr.Logger
func (_e *MockClient_Expecter) CheckProjectExist(port interface{}, sshPrivateKey interface{}, host interface{}, user interface{}, appName interface{}, logger interface{}) *MockClient_CheckProjectExist_Call {
	return &MockClient_CheckProjectExist_Call{Call: _e.mock.On("CheckProjectExist", port, sshPrivateKey, host, user, appName, logger)}
}

func (_c *MockClient_CheckProjectExist_Call) Run(run func(port int32, sshPrivateKey string, host string, user string, appName string, logger logr.Logger)) *MockClient_CheckProjectExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 logr.Logger
		if args[5] != nil {
			arg5 = args[5].(logr.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CheckProjectExist_Call) Return(b bool, err error) *MockClient_CheckProjectExist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockClient_CheckProjectExist_Call) RunAndReturn(run func(port int32, sshPrivateKey string, host string, user string, appName string, logger logr.Logger) (bool, error)) *MockClient_CheckProjectExist_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function for the type MockClient
func (_mock *MockClient) CreateProject(port int32, sshPrivateKey string, host string, user string, appName string, logger logr.Logger) error {
	ret := _mock.Called(port, sshPrivateKey, host, user, appName, logger)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int32, string, string, string, string, logr.Logger) error); ok {
		r0 = returnFunc(port, sshPrivateKey, host, user, appName, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockClient_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - port int32
//   - sshPrivateKey string
//   - host string
//   - user string
//   - appName string
//   - logger logr.Logger
func (_e *MockClient_Expecter) CreateProject(port interface{}, sshPrivateKey interface{}, host interface{}, user interface{}, appName interface{}, logger interface{}) *MockClient_CreateProject_Call {
	return &MockClient_CreateProject_Call{Call: _e.mock.On("CreateProject", port, sshPrivateKey, host, user, appName, logger)}
}

func (_c *MockClient_CreateProject_Call) Run(run func(port int32, sshPrivateKey string, host string, user string, appName string, logger logr.Logger)) *MockClient_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 logr.Logger
		if args[5] != nil {
			arg5 = args[5].(logr.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CreateProject_Call) Return(err error) *MockClient_CreateProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateProject_Call) RunAndReturn(run func(port int32, sshPrivateKey string, host string, user string, appName string, logger logr.Logger) error) *MockClient_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeadToBranch provides a mock function for the type MockClient
func (_mock *MockClient) SetHeadToBranch(port int32, sshPrivateKey string, host string, user string, appName string, branchName string, logger logr.Logger) error {
	ret := _mock.Called(port, sshPrivateKey, host, user, appName, branchName, logger)

	if len(ret) == 0 {
		panic("no return value specified for SetHeadToBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int32, string, string, string, string, string, logr.Logger) error); ok {
		r0 = returnFunc(port, sshPrivateKey, host, user, appName, branchName, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SetHeadToBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeadToBranch'
type MockClient_SetHeadToBranch_Call struct {
	*mock.Call
}

// SetHeadToBranch is a helper method to define mock.On call
//   - port int32
//   - sshPrivateKey string
//   - host string
//   - user string
//   - appName string
//   - branchName string
//   - logger logr.Logger
func (_e *MockClient_Expecter) SetHeadToBranch(port interface{}, sshPrivateKey interface{}, host interface{}, user interface{}, appName interface{}, branchName interface{}, logger interface{}) *MockClient_SetHeadToBranch_Call {
	return &MockClient_SetHeadToBranch_Call{Call: _e.mock.On("SetHeadToBranch", port, sshPrivateKey, host, user, appName, branchName, logger)}
}

func (_c *MockClient_SetHeadToBranch_Call) Run(run func(port int32, sshPrivateKey string, host string, user string, appName string, branchName string, logger logr.Logger)) *MockClient_SetHeadToBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 logr.Logger
		if args[6] != nil {
			arg6 = args[6].(logr.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockClient_SetHeadToBranch_Call) Return(err error) *MockClient_SetHeadToBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SetHeadToBranch_Call) RunAndReturn(run func(port int32, sshPrivateKey string, host string, user string, appName string, branchName string, logger logr.Logger) error) *MockClient_SetHeadToBranch_Call {
	_c.Call.Return(run)
	return _c
}
