@startuml
start
if (metadata payload is not empty) then (yes)
	#lightgreen:Create tag in Jira if doesn't exist;
	#lightgreen:Apply tags to issues;
	#lightgreen:Create issue web links in tickets;
	#lightgrey:Delete JiraIssueMetadata CR;
else (no)
    #lightgreen:Create issue web links in tickets;
    #lightgrey:Delete JiraIssueMetadata CR;
endif
stop

legend
|= |= Component |
|<back:#lightgreen>   </back>| Jira Issue Metadata  |
|<back:#lightgrey>   </back>| Technical  |
endlegend
@enduml