{{- if eq .Values.global.platform "openshift" -}}
apiVersion: rbac.authorization.k8s.io/v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "codebase-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-{{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: edp-{{ .Values.name }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
