{{- if eq .Values.global.platform "openshift" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "codebase-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edp-{{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
