apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    {{- include "codebase-operator.labels" . | nindent 4 }}
  name: edp-codebase-operator-validating-webhook-configuration-{{ .Release.Namespace }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: edp-codebase-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-v2-edp-epam-com-v1-codebasebranch
    failurePolicy: Fail
    name: codebasebranch.epam.com
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - {{ .Release.Namespace }}
    rules:
      - apiGroups:
          - v2.edp.epam.com
        apiVersions:
          - v1
        operations:
          - UPDATE
          - DELETE
        resources:
          - codebasebranchs
        scope: Namespaced
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: edp-codebase-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-v2-edp-epam-com-v1-codebaseimagestream
    failurePolicy: Fail
    name: codebaseimagestream.epam.com
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - {{ .Release.Namespace }}
    rules:
      - apiGroups:
          - v2.edp.epam.com
        apiVersions:
          - v1
        operations:
          - UPDATE
          - DELETE
        resources:
          - codebaseimagestreams
        scope: Namespaced
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: edp-codebase-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-v2-edp-epam-com-v1-gitserver
    failurePolicy: Fail
    name: gitserver.epam.com
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - {{ .Release.Namespace }}
    rules:
      - apiGroups:
          - v2.edp.epam.com
        apiVersions:
          - v1
        operations:
          - UPDATE
          - DELETE
        resources:
          - gitservers
        scope: Namespaced
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: edp-codebase-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-v2-edp-epam-com-v1-codebase
    failurePolicy: Fail
    name: vcodebase.kb.io
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - {{ .Release.Namespace }}
    rules:
      - apiGroups:
          - v2.edp.epam.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - codebases
        scope: Namespaced
    sideEffects: None
