@startuml
start
:Codebase Branch CR;
:Check Parent Codebase;
#lightblue: Check Jenkins Folder;
if (Check new version/ is spec.version in "version history" status) then (no)
    if (EDP Versioning) then (yes)
        #lightblue:Reset Jenkins Build Count;
        #lightblue:Reset Jenkins Last Successful Build;
        :Add spec.version to "version history" status;
    else (no)
    endif
else (yes)
endif
#lightblue: Trigger Jenkins Release Job;
stop

legend
|= |= Component |
|<back:#lightyellow>   </back>| Codebase |
|<back:#lightblue>   </back>| Jenkins |
endlegend
@enduml