@startuml
start
:Jira Fix Version CR;
:Check Parent Jira Server CR;
:Ensure Jira Fix Version;
:Ensure Jira Tickets With Fix Version;
:Delete Jira Fix Version CR;
stop

legend
|= |= Component |
|<back:#lightyellow>   </back>| Jira Fix version |
endlegend
@enduml